name: 'AWS Lambda Update Jar/zip'
description: 'Update a specified lambda with your packaged project jar.'
author: 'Asaf Maoz, asafmaoz1234 <asaf@asafmaoz.com>'
inputs:
  lambda-name:
    description: 'The name of the aws lambda to update'
    required: true
  snapshot-name:
    description: 'The name of the jar (artifactId-version.jar)'
    required: true
  AWS_REGION:
    description: 'Optional if not specified fallbacks to environment variable'
    required: false
  AWS_ACCESS_KEY_ID:
    description: 'Optional if not specified fallbacks to environment variable'
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: 'Optional if not specified fallbacks to environment variable'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'cloud-lightning'
  color: 'gray-dark'
